export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAILURE = 'ORDER_CREATE_FAILURE';
export const ORDER_RESET = 'ORDER_CREATE_RESET';

export const FETCH_ORDER_DETAILS_REQUEST = 'FETCH_ORDER_DETAILS_REQUEST';
export const FETCH_ORDER_DETAILS_SUCCESS = 'FETCH_ORDER_DETAILS_SUCCESS';
export const FETCH_ORDER_DETAILS_FAILURE = 'FETCH_ORDER_DETAILS_FAILURE';

export const FETCH_ORDERS_LIST_REQUEST = 'FETCH_ORDERS_LIST_REQUEST';
export const FETCH_ORDERS_LIST_SUCCESS = 'FETCH_ORDERS_LIST_SUCCESS';
export const FETCH_ORDERS_LIST_FAILURE = 'FETCH_ORDERS_LIST_FAILURE';