export const CART_UPDATE_REQUEST = 'CART_UPDATE_REQUEST';
export const CART_UPDATE_SUCCESS = 'CART_UPDATE_SUCCESS';
export const CART_UPDATE_FAILURE = 'CART_UPDATE_FAILURE';

export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';

export const UPDATE_SHIPPING_ADDRESS_REQUEST = "UPDATE_SHIPPING_ADDRESS_REQUEST";
export const UPDATE_SHIPPING_ADDRESS_SUCCESS = "UPDATE_SHIPPING_ADDRESS_SUCCESS";
export const UPDATE_SHIPPING_ADDRESS_FAILURE = "UPDATE_SHIPPING_ADDRESS_FAILURE";

export const SAVE_PAYMENT_METHOD_REQUEST = 'SAVE_PAYMENT_METHOD_REQUEST';

export const EMPTY_CART_REQUEST = 'EMPTY_CART_REQUEST';
export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS';
export const EMPTY_CART_FAILURE = 'EMPTY_CART_FAILURE';

export const UPDATE = 'UPDATE';
export const REMOVE = 'REMOVE';