export const nobody = {
  appName: "Solar light",
  title: "Solar Light",
  footer: {
    hotline: "Hotline: 097 140 59 31",
    email: "Email: solarhta@gmail.com",
  },
  brandName: "Solar light",
  action: {
    edit: "Sửa",
    delete: "Xóa",
    title: "Hành động",
    continue: "Tiếp tục",
  },
  header: {
    cart: "Giỏ hàng",
    profile: "hồ sơ",
    orderhistory: "lịch sử",
    products: "sản phẩm",
    users: "thành viên",
    orders: "đơn hàng",
    signout: "đăng xuất",
    signin: "đăng nhập",
  },
  product: {
    rating: {
      reviews: "nhận xét",
    },
    price: "Giá",
    description: "Mô tả",
    quantity: "Số lượng",
    inStock: "Còn hàng",
    unavailable: "Hết hàng",
    addToCart: "Thêm vào giỏ hàng",
    product: "Sản phẩm",
    name: "Tên",
    createProduct: "Thêm sản phẩm",
    category: "Danh mục",
    brand: "Nhãn hiệu",
    action: "Hành động",
    edit: "Sửa",
    delete: "Xóa",
    image: "Hình ảnh",
    countInStock: "Số lượng trong kho",
    save: "Thêm",
    chooseImage: "Chọn tệp",
    imageFile: "Tệp hình ảnh",
    status: {
      title: "Trạng thái",
      active: "Kinh Doanh",
      deActive: "Không kinh doanh",
    },
  },
  authen: {
    password: "Mật khẩu",
    passwordPlaceHolder: "Nhập vào mật khẩu",
    confirmPassword: "Xác nhận mật khẩu",
    confirmPasswordPlaceHolder: "Xác nhận mật khẩu",
    signin: "Đăng nhập",
    signup: "Đăng ký",
    alreadyHaveAcc: "Bạn đã có tài khoản?",
    newCustomer: "Chưa có tài khoản?",
  },
  user: {
    profile: "Hồ sơ",
    name: "Họ và tên",
    email: "Email",
    phone: "Số điện thoại",
    address: "Địa chỉ",
    namePlaceHolder: "Nhập vào tên của bạn",
    emailPlaceHolder: "Nhập vào email của bạn",
    phonePlaceHolder: "Nhập vào số điện thoại của bạn",
    addressPlaceHolder: "Nhập vào địa chỉ của bạn",
    update: "Cập nhật",
  },
  admin: {
    users: "Thành viên",
  },
  cart: {
    checkout: "Tiến hành đặt hàng",
    subTotal: "Thành tiền",
    items: "Sản phẩm",
    title: "Giỏ hàng của bạn",
  },
  shipping: {
    title: "Giao hàng",
    header: "Thông tin giao hàng",
    city: "Tỉnh/thành phố",
    continue: "Tiếp tục",
    county: "Phường/xã",
    district: "Quận/huyện",
  },
  payment: {
    title: "Thanh toán",
    continue: "Tiếp tục",
    method: "Phương thức",
    cod: "Thanh toán khi nhận hàng",
  },
  order: {
    items: "Tạm tính",
    shipping: "Phí vận chuyển",
    tax: "Thuế",
    orderTotal: "Thành tiền",
    order: "Đặt hàng",
    Summary: "Thông tin đơn hàng",
    orderDate: "Ngày",
    delivery: {
      title: "Trạng thái",
      yes: "Đã giao",
      no: "Chưa giao",
    },
    action: {
      title: "Hành động",
      cancel: "Hủy",
    },
    total: "Tổng",
    id: "Mã đơn",
    payment: {
      title: "Thanh toán",
      yes: "Đã thanh toán",
      no: "Chưa thanh toán",
    },
  },
  checkout: {
    signin: "Đăng nhập",
    shipping: "Thông tin giao hàng",
    payment: "Thanh toán",
    placeOrder: "Đặt hàng",
  },
};
